---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Chrome.app
    - /Applications/Firefox.app
    - /Applications/Atom.app
    - /Applications/Sublime Text 2.app
    - /Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Michael Moen
    git_user_email: michael@underpantsgnome.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  # - role: npm_package
  #   package_name: grunt
  # - role: npm_package
  #   package_name: bower
  - role: cask_package
    package_name: java
  # - role: brew_package
  #   package_name: android-sdk
  ## databases
  - role: brew_package
    package_name: rbenv

  - role: brew_package
    package_name: ruby-build

  - role: brew_package
    package_name: pow

  - role: brew_package
    package_name: imagemagick

  - role: brew_package
    package_name: ack

  - role: brew_package
    package_name: hub

  - role: brew_package
    package_name: v8

  - role: brew_package
    package_name: qt

  - role: brew_package
    package_name: s3cmd

  - role: brew_package
    package_name: the_silver_searcher
  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: sublime-text

  - role: cask_package
    package_name: flux

  - role: cask_package
    package_name: the-unarchiver

  - role: alfred

  - role: cask_package
    package_name: dropbox

  - role: cask_package
    package_name: google-chrome

  - role: cask_package
    package_name: fluid

  - role: cask_package
    package_name: pg-commander

  - role: cask_package
    package_name: sequel-pro

  - role: cask_package
    package_name: superduper

  - role: cask_package
    package_name: iterm2

  - role: cask_package
    package_name: reeder
